---
- hosts: web
  become: true
  become_user: tomcat
  tasks:
  - name: Install Java
    command: yum install java-1.8.0-openjdk -y
    command: yum install java-1.8.0-openjdk-devel -y
  - lineinfile:
     path: /etc/profile
     line: 'export JRE_HOME=/usr/lib/jvm/jre'
  - lineinfile:
     path: /etc/profile
     line: 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk'
  - name: ensure a list of packages installed
    yum:
     name: "{{ packages }}"
    vars:
     packages:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps
      - tomcat-docs-webapp
      - tomcat-javadoc
     state: present
  - name: Copy fil
    copy:
     src: /home/shiva/tomcat-users.xml
     dest: /usr/share/tomcat/conf/tomcat-users.xml
  - name: enable service tomcat
    systemd:
     name: tomcat
     enabled: yes
  - name: start service tomcat
    systemd:
     name: tomcat
     state: started
     
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/vprofile-v1.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/vprofile-v1.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that vprofile dir exist
    stat:
      path: /usr/share/tomcat/webapps/vprofile
    register: stat_result
  - name: Delete the vprofile dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/vprofile
      state: absent
    when: stat_result.stat.exists == True      
  - name: Deploy War File
    get_url:
       url: http://3.15.32.55:8081/repository/maven-releases/visual/vprofile/8/vprofile-8.war
       dest: /usr/share/tomcat/webapps/
  - name: Start Tomcat
    service: name=tomcat state=started
