---
- hosts: web
  become: true
  tasks:     
  - name: Stop Tomcat
    service: name=tomcat state=stopped
 
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/vprofile-v1.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/vprofile-v1.war
      state: absent
    when: stat_result.stat.exists == True
 
  - name: Deploy War File
    get_url:
       url: http://18.222.248.18:8081/service/rest/v1/search/assets/download?sort=version&direction=desc&repository=maven-releases&maven.groupId=com.visualpathit&maven.artifactId=vprofile&maven.extension=war
       dest: /var/lib/tomcat/webapps/vprofile-v1.war
       mode: 0755
       group: root
       owner: tomcat

  - name: Start Tomcat
    service: name=tomcat state=started
