---
- hosts: web
  become: true
  tasks:     
  - name: Stop Tomcat
    service: name=tomcat state=stopped
 
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/vprofile-v1.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/vprofile-v1.war
      state: absent
    when: stat_result.stat.exists == True
 
  - name: Deploy War File
    shell: curl -L -o /usr/share/tomcat/webapps/vprofile.v1.war -u tomcat:tomcat "http://18.188.6.70:8081/service/rest/v1/search/assets/download?sort=version&direction=desc&repository=maven-releases&maven.groupId=com.visualpathit&maven.artifactId=vprofile&maven.extension=war"
 #        url: http://18.188.6.70:8081/service/rest/v1/search/assets/download?sort=version&direction=desc&repository=maven-releases&maven.groupId=com.visualpathit&maven.artifactId=vprofile&maven.extension=war
 #         dest: tomcat@13.58.188.0:/usr/share/tomcat/webapps/vprofile-v1.war
      
  - name: Start Tomcat
    service: name=tomcat state=started
